### ISSUE TITLE
Make 'add' the default action without explicit subcommand

### ISSUE THREAD

**Issue by crispinb** [crispinb/cvcap#38]
ie. `cvcap "task" [other optional args]` should do the same as ` cvcap add "task" [other optional args]`

**Comment by pacak** [comment]
For that you can have an alternative with just a positional `String` argument and any extra arguments you might have:

```rust
pub enum Command {
    ...
    QuickAdd(Extra, String)
    ...
}

let quick_task = positional("TASK").help("quick positional task ...");
let quick_task_command = construct!(Command::QuickAdd(extra(), quick_task));
...
let subcommand = construct!([
    quick_task_command,
    add_task_command,
```

(or even parse it into AddTask directly by using `map` a tuple later)

**Comment by crispinb** [comment]
Thanks, that's very helpful. Again! Also thanks for the Rust Magazine article you recommended in another issue. 
It helped make command line parsing, which previously seemed like just a chore to get out of the way, into something interesting to think & read about.

**Comment by crispinb** [comment]
@pacak - Is there a way to prevent a `Parser` impl consuming its matched token?

I would like to do something similar to your `batteries::cargo_helper`, roughly:

```rust
        let quick_add = positional::<String>("TASK_CONTENT")
            .optional()
            .catch()
            .hide();
        let add_task_parser = action::AddTask::parser();
        let quick_add_command = construct!(quick_add, add_task_parser).map(|p| p.1);
```

But the positional arg is also needed by the AddTask parser. It would be nice if I could tell the positional parser 'if you match, leave your token to be matched again by the next parser'.

I prefer this approach to creating a separate command, though that will work if necessary.

**Comment by pacak** [comment]
`cargo_helper` consumes if something matches or leaves it as is otherwise. You probably don't want it either. The idea for multiple parsers for `AddTask` is that only one of them succeeds. Either one with explicit `add` command or without it. If you really want to see what can be matched without consuming it - you can take a look at how shell completion is implemented in `bpaf_cauwugo`. There items are consumed and placed into `Rc`s, you can try to place them into `Rc` with `guard` and then reject it by the same guard.
